#!/usr/bin/env bash
#
# S7-03 / S7-04 — the four provisioning gates the hosting mapping carried as [UNVERIFIED].
# Runs ON the private admin host, invoked by SSM. Never run from a laptop: the database
# is not reachable from outside the VPC, by design (M-11).
#
# THIS IS A PROVISIONING STEP, NOT A TEST, DESPITE THE NAME. It CREATES the fru database
# with the ICU locale (which cannot be changed afterwards), CREATES the privileged
# fru_migrator role, and transfers database ownership to it. flyway:migrate cannot connect
# at all until this has run. It reports its results as gates, which is where the name comes
# from. See infra/aws/README.md for where it sits in the real order.
#
# RE-RUNNING ROTATES A LIVE CREDENTIAL. 01-network.sh and 02-database.sh refuse to run a
# second time and say so; this one does not. On a re-run it resets fru_migrator's password
# and overwrites the stored secret — the "SKIP  fru_migrator existed; password reset"
# branch below. Anything holding the old password breaks. Do not re-run this to re-check
# something: read the transcript from the run that provisioned the database instead.
#
# Requires in the environment: DB_ENDPOINT, MASTER_SECRET_ARN.
#
# CREDENTIAL DISCIPLINE. The RDS master password is read from Secrets Manager into this
# process and used via PGPASSWORD. The fru_migrator password is generated by AWS, written
# straight to Secrets Manager, and applied through a 0600 temp file rather than a command
# argument — a password in argv is visible in `ps` to anything else on the box. Neither
# password is ever echoed, so SSM's captured output (which lands in a transcript) carries
# results only. That is a hard rule, not a nicety.
#
# REPORTING CONTRACT. Under SSM automation a FAIL branch that still returns 0 is reported
# as a successful invocation, so every gate failure sets RC and the script exits non-zero.
# The checks whose verdict is computed in SQL are READ by the shell (check_sql) instead of
# printed and ignored — a psql error there produces neither the word PASS nor the word
# FAIL, and that absence is a failure, not a pass. Found by review.
#
# The gates, and why each one is here:
#   M-3  ar-x-icu must resolve, AND the fru database must default to the ICU provider.
#        RDS accepts no initdb arguments, so this is done by CREATE DATABASE, not at
#        instance creation. Skipping it changes Arabic sort order without failing.
#   M-5  the RDS main user must be able to create login roles and hand the database over
#        to fru_migrator. Plausible but unconfirmed until run.
#   M-4  CREATE EVENT TRIGGER. THE gate. RDS grants no true superuser, and PostgreSQL's
#        check for this is hard-coded with no GRANT-based delegation. If it fails, Layer 3
#        of the audit append-only enforcement cannot be installed, flyway:migrate still
#        succeeds, the app still starts, and DDL against schema audit is unguarded — R-028's
#        silent-skip made permanent. A failure here STOPS the session.
set -uo pipefail
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-eu-central-1}"
umask 077

RC=0

# Read a verdict that is computed in SQL. The three checks that use this print a literal
# 'PASS ...' or 'FAIL ...' as their query RESULT. Before this they went to the transcript
# and were never inspected, so a FAIL — or a psql error, which yields neither word — left
# the script exiting 0. Found by review.
check_sql() { # $1 = gate label, then psql arguments
  local label="$1"; shift
  local out prc
  out=$(psql "$@" 2>&1); prc=$?
  printf '%s\n' "$out"
  if [ "$prc" -ne 0 ]; then
    echo "FAIL  $label: psql exited $prc — no verdict was produced"
    RC=1; return 1
  fi
  case "$out" in
    *FAIL*) echo "FAIL  $label: the check above reported FAIL"; RC=1; return 1 ;;
    *PASS*) return 0 ;;
    *)      echo "FAIL  $label: no verdict in the output above"; RC=1; return 1 ;;
  esac
}

CREDS=$(aws secretsmanager get-secret-value --secret-id "$MASTER_SECRET_ARN" --query SecretString --output text)
PGUSER=$(printf '%s' "$CREDS" | jq -r .username); export PGUSER
PGPASSWORD=$(printf '%s' "$CREDS" | jq -r .password); export PGPASSWORD
unset CREDS
export PGHOST="$DB_ENDPOINT" PGPORT=5432 PGDATABASE=postgres PGSSLMODE=require

echo "=== connectivity (TLS enforced) ==="
psql -Atc "SELECT version();" || { echo "FAIL: cannot connect"; exit 1; }
psql -Atc "SELECT 'ssl='||ssl||' cipher='||coalesce(version,'-') FROM pg_stat_ssl WHERE pid=pg_backend_pid();"

echo
echo "=== GATE M-3a: is the ar-x-icu collation resolvable? ==="
check_sql "M-3a" -Atc "SELECT CASE WHEN count(*)=1 THEN 'PASS  ar-x-icu present in pg_collation' ELSE 'FAIL  ar-x-icu MISSING' END FROM pg_collation WHERE collname='ar-x-icu';"

echo
echo "=== GATE M-3b: create fru with ICU as the DEFAULT locale provider ==="
if psql -v ON_ERROR_STOP=1 -q -c "CREATE DATABASE fru TEMPLATE template0 ENCODING UTF8 LOCALE_PROVIDER icu ICU_LOCALE 'ar';" 2>/tmp/g_b; then
  echo "PASS  CREATE DATABASE fru ... LOCALE_PROVIDER icu ICU_LOCALE 'ar'"
else
  if grep -qi "already exists" /tmp/g_b; then
    echo "SKIP  fru already exists"
  else
    echo "FAIL  CREATE DATABASE refused:"; cat /tmp/g_b; RC=1
  fi
fi
# datlocprovider is type "char", which has no unique || operator against unknown — cast it.
# 'i' = icu, 'c' = libc, 'b' = builtin. Anything but 'i' means the DEFAULT collation
# silently disagrees with docker-compose's --locale-provider=icu, which is the exact
# failure M-3 exists to prevent: Arabic sort order differs and nothing errors.
check_sql "M-3b default provider" -Atc "SELECT 'datlocprovider='||datlocprovider::text||'  encoding='||pg_encoding_to_char(encoding)||'  datlocale='||coalesce(datlocale,'(null)')||'  '||CASE WHEN datlocprovider='i' THEN 'PASS default provider is ICU' ELSE 'FAIL default provider is NOT ICU' END FROM pg_database WHERE datname='fru';"

echo
echo "=== GATE M-3c: is ICU ordering actually in effect, or only nominally configured? ==="
# A differential test. Sorting alef variants by codepoint (COLLATE "C") gives
# 0622 0623 0625 0627; the Arabic ICU tailoring treats them as variants of alef and orders
# them differently. Identical output from both would mean ICU is not really collating.
# Characters are built with chr() so no non-ASCII byte has to survive transport, and the
# result is printed as hex codepoints so no terminal encoding can garble the evidence.
#
# BOTH orders must be non-empty before they are compared. If only the ar-x-icu query fails
# — which is exactly the condition this gate exists to detect — ICU_ORDER is empty, C_ORDER
# is not, the two "differ", and the old code printed PASS. Found by review.
ICU_ORDER=$(psql -d fru -Atc "SELECT string_agg(to_hex(ascii(w)),' ' ORDER BY w COLLATE \"ar-x-icu\") FROM (VALUES (chr(1570)),(chr(1571)),(chr(1573)),(chr(1575))) v(w);" 2>/tmp/g_icu)
C_ORDER=$(psql -d fru -Atc "SELECT string_agg(to_hex(ascii(w)),' ' ORDER BY w COLLATE \"C\") FROM (VALUES (chr(1570)),(chr(1571)),(chr(1573)),(chr(1575))) v(w);" 2>/tmp/g_cord)
echo "      ar-x-icu order : $ICU_ORDER"
echo "      C (codepoint)  : $C_ORDER"
if [ -z "$ICU_ORDER" ] || [ -z "$C_ORDER" ]; then
  echo "FAIL  a collation query returned nothing — the comparison below would be meaningless:"
  cat /tmp/g_icu /tmp/g_cord 2>/dev/null
  RC=1
elif [ "$ICU_ORDER" != "$C_ORDER" ]; then
  echo "PASS  ICU collation demonstrably changes ordering (differs from codepoint order)"
else
  echo "FAIL  ar-x-icu ordered identically to codepoint order — ICU is not collating"
  RC=1
fi

echo
echo "=== GATE M-5: create fru_migrator, then transfer database ownership ==="
MIGPW=$(aws secretsmanager get-random-password --password-length 40 --exclude-punctuation --require-each-included-type --query RandomPassword --output text)
# This script runs under `set -uo pipefail` WITHOUT -e, so a failed generation would leave
# MIGPW empty and execution would continue to CREATE ROLE ... PASSWORD '' and then print PASS.
# A passwordless privileged login role reported as a passing gate is the worst possible
# outcome of this block, so it is checked explicitly rather than trusted. Found by review.
if [ -z "${MIGPW:-}" ]; then
  echo "FAIL  password generation returned empty - refusing to create a passwordless role"
  exit 1
fi
# The password is stored BEFORE the role is created, deliberately: a store that failed after
# the role existed would leave a live privileged role whose password is recorded nowhere.
# Both write paths therefore exit on failure rather than continuing. create-secret was
# missing that check, so a failed FIRST creation used to fall through to CREATE ROLE and
# produce exactly the unrecorded-credential case this ordering exists to prevent; the
# rotation path was already covered. Moving the write after role creation would not fix
# this, it would only relocate the hole. Found by review.
if aws secretsmanager describe-secret --secret-id fru/staging/db/migrator >/dev/null 2>&1; then
  aws secretsmanager put-secret-value --secret-id fru/staging/db/migrator --secret-string "$MIGPW" >/dev/null \
    || { echo "FAIL  could not store the migrator password"; exit 1; }
else
  aws secretsmanager create-secret --name fru/staging/db/migrator \
    --description "fru_migrator DB login. Injected into the migration task only, never the app (M-6)." \
    --secret-string "$MIGPW" >/dev/null \
    || { echo "FAIL  could not file the migrator password - refusing to create a role whose password is stored nowhere"; exit 1; }
fi
# printf is a shell builtin, so the password never appears in argv or in `ps`.
printf "CREATE ROLE fru_migrator LOGIN CREATEROLE PASSWORD '%s';\n" "$MIGPW" > /tmp/g_role.sql
printf "ALTER ROLE fru_migrator LOGIN CREATEROLE PASSWORD '%s';\n" "$MIGPW" > /tmp/g_role_alt.sql
unset MIGPW
if psql -v ON_ERROR_STOP=1 -q -f /tmp/g_role.sql 2>/tmp/g_c; then
  echo "PASS  CREATE ROLE fru_migrator LOGIN CREATEROLE"
elif grep -qi "already exists" /tmp/g_c && psql -v ON_ERROR_STOP=1 -q -f /tmp/g_role_alt.sql 2>/dev/null; then
  echo "SKIP  fru_migrator existed; password reset"
else
  echo "FAIL  cannot create login roles:"; cat /tmp/g_c; RC=1
fi
shred -u /tmp/g_role.sql /tmp/g_role_alt.sql 2>/dev/null || rm -f /tmp/g_role.sql /tmp/g_role_alt.sql

if psql -v ON_ERROR_STOP=1 -q -c "ALTER DATABASE fru OWNER TO fru_migrator;" 2>/tmp/g_d; then
  echo "PASS  ALTER DATABASE fru OWNER TO fru_migrator"
else
  echo "FAIL  ownership transfer refused:"; cat /tmp/g_d; RC=1
fi
psql -Atc "SELECT 'fru owner is '||pg_catalog.pg_get_userbyid(datdba) FROM pg_database WHERE datname='fru';"

echo
echo "=== GATE M-4: CREATE EVENT TRIGGER as the RDS main user  <<< THE CRITICAL ONE >>> ==="
if psql -d fru -v ON_ERROR_STOP=1 -q 2>/tmp/g_e <<'SQL'
CREATE OR REPLACE FUNCTION public.fru_probe_evt() RETURNS event_trigger LANGUAGE plpgsql AS $f$ BEGIN END $f$;
CREATE EVENT TRIGGER fru_probe_guard ON ddl_command_end EXECUTE FUNCTION public.fru_probe_evt();
SQL
then
  # The statement succeeding is not the gate; the trigger EXISTING is. This verdict is
  # computed in SQL and used to be printed without ever being read, so the STOP gate's own
  # confirmation could report FAIL and the script would still exit 0. Found by review.
  if check_sql "M-4" -d fru -Atc "SELECT CASE WHEN count(*)=1 THEN 'PASS  CREATE EVENT TRIGGER is permitted on RDS' ELSE 'FAIL  statement succeeded but no trigger exists' END FROM pg_event_trigger WHERE evtname='fru_probe_guard';"; then
    M4_OK=1
  else
    M4_OK=0
  fi
  psql -d fru -q -c "DROP EVENT TRIGGER IF EXISTS fru_probe_guard;" >/dev/null 2>&1
  psql -d fru -q -c "DROP FUNCTION IF EXISTS public.fru_probe_evt();" >/dev/null 2>&1
  # Confirm rather than announce. Both DROPs discard their output, so a failed drop would
  # leave fru_probe_guard firing on EVERY DDL in this database while the transcript claimed
  # the probe was cleaned up. Found by review.
  if psql -d fru -Atc "SELECT count(*) FROM pg_event_trigger WHERE evtname='fru_probe_guard';" 2>/dev/null | grep -q '^0$'; then
    echo "      probe objects removed; the real Layer 3 install is S7-06, after migration"
  else
    echo "FAIL  the probe event trigger is STILL PRESENT - it will fire on every DDL in fru"
    RC=1
  fi
  if [ "$M4_OK" -ne 1 ]; then
    echo "FAIL  M-4 could not be confirmed — this is the STOP condition"
    rm -f /tmp/g_b /tmp/g_c /tmp/g_d /tmp/g_e /tmp/g_icu /tmp/g_cord
    exit 1
  fi
else
  echo "FAIL  CREATE EVENT TRIGGER REFUSED — this is the STOP condition:"
  cat /tmp/g_e
  # Exit non-zero. Under SSM automation a FAIL branch that still returns 0 is reported as a
  # successful invocation, and this is the one gate whose failure is meant to stop the
  # session outright. Found by review.
  rm -f /tmp/g_b /tmp/g_c /tmp/g_d /tmp/g_e /tmp/g_icu /tmp/g_cord
  exit 1
fi

rm -f /tmp/g_b /tmp/g_c /tmp/g_d /tmp/g_e /tmp/g_icu /tmp/g_cord
echo
if [ "$RC" -ne 0 ]; then
  echo "=== gates complete WITH FAILURES (exit 1) ==="
else
  echo "=== gates complete ==="
fi
exit "$RC"
