#!/usr/bin/env bash
#
# S7-05 — the application and seal database credentials (M-13).
#
# WHY THIS FILE EXISTS AT ALL. fru_migrator's password is filed by 04-db-gates.sh, because
# that is the script that creates the role. These two were originally created by an ad-hoc
# command line during the live run and by nothing in this directory — which made two of the
# three claimed credentials unreproducible while infra/aws/ advertised itself as the record
# of what was provisioned. Found by review; this closes that gap rather than restating it.
#
# Each value is generated by AWS and written straight to Secrets Manager. It is never
# printed, never interpolated into a visible command, and never returned to the caller.
# The passwords are consumed as Flyway placeholders (V0001 creates fru_app, V0030 creates
# fru_sealer), so the roles themselves are made by migration, not here.
#
# M-6's separation is expressed by WHICH TASK DEFINITION references WHICH ARN, enforced by
# IAM — not by a file anyone re-reads:
#   fru/staging/db/app     -> the running service task, and nothing else
#   fru/staging/db/sealer  -> the scheduled seal task, and nothing else
#   fru/staging/db/migrator-> the one-shot migration task, and nothing else
#
# Idempotent: an existing secret is left alone, NOT rotated. Rotating fru_app's password here
# without also ALTERing the role would break a running service, so this script refuses to be
# the thing that silently does that.
#
# Usage:  AWS_PROFILE=fru-deploy bash infra/aws/06-secrets.sh
set -euo pipefail

AWS="${AWS_CLI:-/c/Program Files/Amazon/AWSCLIV2/aws.exe}"
export AWS_PAGER=""
export MSYS_NO_PATHCONV=1
REGION="${AWS_REGION:-eu-central-1}"

aws_() { "$AWS" --region "$REGION" "$@"; }

create_if_absent() { # $1 = secret name, $2 = description
  if aws_ secretsmanager describe-secret --secret-id "$1" >/dev/null 2>&1; then
    echo "exists (left alone): $1"
    return 0
  fi
  local pw
  pw=$(aws_ secretsmanager get-random-password \
        --password-length 40 --exclude-punctuation --require-each-included-type \
        --query RandomPassword --output text)
  # An empty generation would otherwise file an empty secret that a later migration would
  # happily turn into a passwordless role. Same defect class as 04-db-gates.sh's M-5 block.
  if [ -z "$pw" ]; then
    echo "FAIL  password generation returned empty for $1" >&2
    return 1
  fi
  aws_ secretsmanager create-secret --name "$1" --description "$2" --secret-string "$pw" \
    --tags Key=Project,Value=fru Key=Environment,Value=staging >/dev/null
  unset pw
  echo "created: $1"
}

create_if_absent fru/staging/db/app \
  "fru_app runtime login. Owns nothing; INSERT+SELECT on audit only. The ONLY database secret in the service task definition (M-6)."
create_if_absent fru/staging/db/sealer \
  "fru_sealer audit-seal login. Injected into the scheduled seal task only; the application never connects as this role."

echo
echo "== secret names in this account (names only, never values) =="
aws_ secretsmanager list-secrets --query 'SecretList[].Name' --output text

cat <<'NOTE'

NOT created here, deliberately: UQUDO_CLIENT_ID and UQUDO_CLIENT_SECRET. They are the tenant's
own credentials and must be entered by the product owner directly, never relayed through a
session. A placeholder secret would be worse than an absent one -- it would let a misconfigured
task start against a wrong value instead of failing at startup, which is the single failure mode
the no-default selector design exists to prevent.
NOTE
