package com.sfbank.bayanati.reference.domain;

import java.nio.charset.StandardCharsets;
import java.util.List;

/**
 * Builds the exact document bytes AD-002f's {@code content_hash} is defined over (research report
 * §4.3: "SHA-256 over the exact UTF-8 bytes of the list document ... before any transport
 * content-coding"). This is the whole integrity primitive — a client hashes what it received and
 * compares to the manifest, so there is no client-side canonical-JSON implementation anywhere.
 *
 * <p><strong>Hand-rolled, not a general-purpose JSON library</strong> — matching this codebase's
 * own precedent, {@code audit.domain.CanonicalJson} ("this project already built CanonicalJson
 * rather than trust a general-purpose serializer's key order," cited directly by the research
 * report as the reasoning for storing generated bytes rather than regenerating them per request).
 * Key order here is fixed by the code, not sorted or library-dependent, so two runs of the same
 * Java code against the same rows always produce byte-identical output.
 *
 * <p><strong>{@code extra} is embedded verbatim, not re-parsed.</strong> {@link
 * ReferenceDocumentItem#extraJson} arrives as the raw text Postgres's {@code extra::text} cast
 * already produced — already valid JSON. The research report rejected doing the document's own
 * canonicalisation in SQL partly because jsonb's internal text-output key ordering has no
 * documented cross-version stability guarantee (§4.2/§8); that concern is about using jsonb's text
 * form as a portable canonicalisation *contract*, not about whether one PostgreSQL instance
 * produces the same bytes for the same row content when asked twice in the same generation run — it
 * does, deterministically. Re-parsing and re-serialising {@code extra} here would buy nothing: this
 * class already owns the document end to end, and the one property that actually matters — this
 * Java code, run again against unchanged rows, produces identical output — holds regardless of what
 * jsonb's own text form looks like.
 *
 * <p>Pure: no Spring, no database, no clock — a plain JUnit test exercises every branch. A static
 * utility, not an instantiated bean, matching {@code audit.domain.CanonicalJson}'s own shape — this
 * class holds no state, so there is nothing a Spring context would ever need to wire.
 */
public final class ReferenceDocumentGenerator {

  private ReferenceDocumentGenerator() {}

  /**
   * @throws IllegalArgumentException if any string value contains U+0000 or an unpaired UTF-16
   *     surrogate — both would make the emitted bytes not well-formed JSON
   */
  public static byte[] generate(ReferenceListDocumentInput input) {
    StringBuilder out = new StringBuilder();
    ObjectWriter doc = new ObjectWriter(out);
    doc.field("listCode", input.listCode());
    doc.rawField("version", Integer.toString(input.version()));
    doc.rawField("itemCount", Integer.toString(input.itemCount()));
    doc.field("nameAr", input.nameAr());
    doc.field("nameEn", input.nameEn());
    doc.rawField("isHierarchical", Boolean.toString(input.isHierarchical()));
    doc.field("rootItemCode", input.rootItemCode());
    doc.arrayField("items", input.items(), ReferenceDocumentGenerator::appendItem);
    doc.close();
    return out.toString().getBytes(StandardCharsets.UTF_8);
  }

  private static void appendItem(StringBuilder out, ReferenceDocumentItem item) {
    ObjectWriter obj = new ObjectWriter(out);
    obj.field("itemCode", item.itemCode());
    obj.field("parentCode", item.parentCode());
    obj.field("labelAr", item.labelAr());
    obj.field("labelEn", item.labelEn());
    obj.field("searchAr", item.searchAr());
    obj.field("searchEn", item.searchEn());
    obj.rawField("sortOrdinal", Integer.toString(item.sortOrdinal()));
    obj.rawField("isActive", Boolean.toString(item.isActive()));
    obj.rawField("extra", item.extraJson() == null ? "null" : item.extraJson());
    obj.close();
  }

  /**
   * Tracks "first member written yet" so commas are placed correctly with no trailing-comma edit.
   */
  private static final class ObjectWriter {
    private final StringBuilder out;
    private boolean firstMember = true;

    ObjectWriter(StringBuilder out) {
      this.out = out;
      out.append('{');
    }

    void field(String key, String stringValueOrNull) {
      beforeMember();
      appendJsonString(out, key);
      out.append(':');
      if (stringValueOrNull == null) {
        out.append("null");
      } else {
        appendJsonString(out, stringValueOrNull);
      }
    }

    void rawField(String key, String rawValue) {
      beforeMember();
      appendJsonString(out, key);
      out.append(':').append(rawValue);
    }

    <T> void arrayField(String key, List<T> items, ItemAppender<T> appender) {
      beforeMember();
      appendJsonString(out, key);
      out.append(":[");
      boolean firstItem = true;
      for (T item : items) {
        if (!firstItem) {
          out.append(',');
        }
        firstItem = false;
        appender.append(out, item);
      }
      out.append(']');
    }

    void close() {
      out.append('}');
    }

    private void beforeMember() {
      if (!firstMember) {
        out.append(',');
      }
      firstMember = false;
    }
  }

  @FunctionalInterface
  private interface ItemAppender<T> {
    void append(StringBuilder out, T item);
  }

  /** Same escape set CanonicalJson uses (RFC 8785 §3.2.2.2), plus the same two hard rejections. */
  private static void appendJsonString(StringBuilder out, String value) {
    out.append('"');
    for (int i = 0; i < value.length(); i++) {
      char c = value.charAt(i);
      switch (c) {
        case '"' -> out.append("\\\"");
        case '\\' -> out.append("\\\\");
        case '\b' -> out.append("\\b");
        case '\f' -> out.append("\\f");
        case '\n' -> out.append("\\n");
        case '\r' -> out.append("\\r");
        case '\t' -> out.append("\\t");
        default -> {
          if (c == 0) {
            throw new IllegalArgumentException("a reference document string cannot contain U+0000");
          }
          if (Character.isSurrogate(c) && !isWellFormedPair(value, i)) {
            throw new IllegalArgumentException(
                "a reference document string cannot contain an unpaired surrogate at index " + i);
          }
          if (c < 0x20) {
            out.append(String.format("\\u%04x", (int) c));
          } else {
            out.append(c);
          }
        }
      }
    }
    out.append('"');
  }

  private static boolean isWellFormedPair(String value, int i) {
    char c = value.charAt(i);
    if (Character.isHighSurrogate(c)) {
      return i + 1 < value.length() && Character.isLowSurrogate(value.charAt(i + 1));
    }
    return i > 0 && Character.isHighSurrogate(value.charAt(i - 1));
  }
}
