package com.sfbank.bayanati.printedform.domain;

import java.util.Locale;

/**
 * Where one printed value came from.
 *
 * <p><strong>No longer printed beside a text value.</strong> Ticket 04 decision 2 had the form
 * print both values tagged by origin wherever two sources existed. The product owner read that on a
 * real render and ruled on 2026-09-14 that each field takes ONE source instead, so there is no
 * second value for a tag to distinguish and the body of the form carries none.
 *
 * <p>Still needed in two places: the assembler uses it to decide which source to read each field
 * from, and {@link #ofScannedDocument} maps a scanned document type to the document that produced
 * it.
 *
 * <h2>UQUDO IS NOT A SOURCE, and never appears on the form</h2>
 *
 * <p>Product-owner correction, 2026-09-14 (S8-33). This enum's first draft had {@code
 * UQUDO_PASSPORT}, {@code UQUDO_NATIONAL_ID} and a bare {@code UQUDO}, and printed all three by
 * name. <strong>Uqudo is a tool, not a source.</strong> What a branch officer reading a filed form
 * needs to know is which DOCUMENT a value was read from — a passport or a national ID card —
 * because that is the thing they could ask the customer to produce again. The name of the vendor
 * whose SDK did the scanning tells them nothing, and puts a supplier's brand on the bank's own
 * filing document.
 *
 * <p>So a scanned value's origin is «جواز سفر» or «بطاقة قومية». Only the labels changed; the
 * mapping from the scanned document type still happens in {@link #ofScannedDocument}.
 */
public enum FieldOrigin {

  /** The customer typed or chose it, stages 3-6. Source S3. */
  CUSTOMER("إدخال العميل"),

  /** Source S1, {@code app.registry_result}. */
  CIVIL_REGISTRY("السجل المدني"),

  /** Source S2, read from a scanned passport. */
  PASSPORT("جواز سفر"),

  /** Source S2, read from a scanned national ID card. */
  NATIONAL_ID("بطاقة قومية"),

  /**
   * Source S2, where the scanned document type is not one of the two above or was not recorded.
   *
   * <p>Deliberately generic rather than defaulting to one of the specific labels: naming the wrong
   * document on a filed form is worse than naming none, because a branch officer would then ask the
   * customer for a document nobody ever scanned.
   */
  IDENTITY_DOCUMENT("وثيقة الهوية"),

  /**
   * Generated by this system, never entered by anyone — field 1 (form date) is the only one.
   * field-provenance.md marks its Source as "System" rather than S1/S2/S3.
   */
  SYSTEM("النظام");

  private final String tag;

  FieldOrigin(String tag) {
    this.tag = tag;
  }

  /**
   * The Arabic name of the source. NOT printed beside a value any more (see above); it survives for
   * the assembler and for anyone reading what a field or an image box actually holds. Never a
   * vendor or tool name.
   */
  public String tag() {
    return tag;
  }

  /**
   * The origin matching a scanned document type.
   *
   * @param documentType {@code app.scan_result.document_type}, which may be null on a profile with
   *     no scan at all (a manually completed one — ticket 04 decision 7)
   */
  public static FieldOrigin ofScannedDocument(String documentType) {
    if (documentType == null) {
      return IDENTITY_DOCUMENT;
    }
    return switch (documentType.trim().toUpperCase(Locale.ROOT)) {
      case "PASSPORT" -> PASSPORT;
      case "SDN_ID", "NATIONAL_ID" -> NATIONAL_ID;
      default -> IDENTITY_DOCUMENT;
    };
  }
}
